config:
  name: hobot-x5-6.1
  kind: kernel
  type: vendor
  branch: x5-kernel
  maintainers:
    - { github: wentywenty, name: wentywenty }
  patches-to-git:
    do-not-commit-files:
      - "MAINTAINERS"
